export const ELEMENTS = {
    HEADER: {
        container: '.vtex-sticky-layout-0-x-container vtex-sticky-layout-0-x-container--sticky-header',
        btnLogo: '.vtex-flex-layout-0-x-flexRowContent--main-header > :nth-child(1) > .vtex-flex-layout-0-x-flexCol',
        containerCookes: '.arcelormittal-cookies-consent-0-x-cookies-consent__modal flex flex-column justify-center items-center fw5',
        btnAcceptCookies: '.arcelormittal-cookies-consent-0-x-cookies-consent__modal-allow',
        btnDenyCookies:'.arcelormittal-cookies-consent-0-x-cookies-consent__modal-deny',
        inputSearch: '#downshift-0-input',
        listResult: '.vtex-store-components-3-x-resultsList',
        btnLogin:'.vtex-flex-layout-0-x-flexRow--login .vtex-button.t-action.c-action-primary',
        btnLoginEmail: ':nth-child(1) > .vtex-login-2-x-button > .vtex-button',
        btnEmailPassword: ':nth-child(2) > .vtex-login-2-x-button > .vtex-button',
        btnSocial:':nth-child(3) > .vtex-login-2-x-button > .vtex-button',
        btnShopkeeper: '#menu-item-seller-dropdown',
        btnMiniCart: '.pa4 > .vtex-button',
        containerMinicartEmpty: '.vtex-minicart-2-x-minicartEmptyStateContainer',
        containerHeader: 'nav.vtex-menu-2-x-menuContainerNav',
        containerUlHeader:'ul.vtex-menu-2-x-menuContainer',
        containerLiheader: 'li.vtex-menu-2-x-menuItem',
        containerMenuHeader:'.vtex-menu-2-x-styledLinkContent',
    },
    BANNER: {
        containerBanner: 'section[aria-label="Banner principal da home"]',
        containerImgFirst: '.vtex-slider-layout-0-x-slide--main-banner-image-slider--visible img',
        imgFirst:'013ff4cc-9864-49c1-92b6-eac6b96f37b9___9e6edf8599b09513aa081ad5f6f65302.webp',
        arrowLeft: '.vtex-slider-layout-0-x-sliderRightArrow',
    },
    ADVANTAGE_RULER: {
        rulerContainer: 'vtex-flex-layout-0-x-flexRow vtex-flex-layout-0-x-flexRow--advantages-block',
        parcelIn10x: ':nth-child(1) > .vtex-flex-layout-0-x-flexCol--advantages-item',
        whatsapp: ':nth-child(2) > .vtex-flex-layout-0-x-flexCol--advantages-item',
        pickup: ':nth-child(3) > .vtex-flex-layout-0-x-flexCol--advantages-item',
        discount: ':nth-child(4) > .vtex-flex-layout-0-x-flexCol--advantages-item',
    },
    BEST_SELLERS_SHELF: {
        containerShelf: '.vtex-flex-layout-0-x-flexRow--shelf-home-best-sellers',
        highlightProduct: 'span.vtex-product-highlights-2-x-productHighlightText--fivePercentTicket',
        imgProduct: 'img.vtex-product-summary-2-x-image',
        nameProduct: '.vtex-product-summary-2-x-productNameContainer--product-card',
        priceProduct: '.arcelormittal-product-price-custom-0-x-productPrice',
        discountTicket:'div.vtex-rich-text-0-x-wrapper--ticket-discount',
        discountPercentage: 'div.vtex-rich-text-0-x-wrapper--priceSavingText',
        buttonAdd: 'button.vtex-button',
    },
    HIGHLIGHT_SHELF: {
        containerShelf: '.vtex-flex-layout-0-x-flexRow--shelf-home-prominent-products',
        highlightProduct: 'span.vtex-product-highlights-2-x-productHighlightText--fivePercentTicket',
        imgProduct: 'img.vtex-product-summary-2-x-image',
        nameProduct: '.vtex-product-summary-2-x-productNameContainer--product-card',
        priceProduct: '.arcelormittal-product-price-custom-0-x-productPrice',
        discountTicket:'div.vtex-rich-text-0-x-wrapper--ticket-discount',
        discountPercentage: 'div.vtex-rich-text-0-x-wrapper--priceSavingText',
        buttonAdd: 'button.vtex-button',
    },
    CATEGORY_CAROUSEL: {
        containerCarousel: '.vtex-flex-layout-0-x-flexRow--carouselCategoryContainer',
        titleCarousel: '.vtex-rich-text-0-x-heading--carouselCategoryTitle',
        subtitleCarousel: '.vtex-rich-text-0-x-paragraph--carouselCategorySubtitle',
        containerCategory: '.vtex-slider-layout-0-x-sliderTrack--carouselCategorySlider',
        categoryText: '.vtex-rich-text-0-x-container--carousel-category-text',
    },
    BANNER_FRAUD: {
        bannerContainer: '.vtex-flex-layout-0-x-flexRow.vtex-flex-layout-0-x-flexRow--imageUnicBanner',
        imgLink: ".vtex-store-components-3-x-imageElementLink",
        imgContainer: 'a[href="/fique-em-alerta"]',
    },
    LAUNCH_PRODUCT_SHELF: {
        containerShelf: ':nth-child(9) > .vtex-flex-layout-0-x-flexRow',
        highlightProduct: 'span.vtex-product-highlights-2-x-productHighlightText--fivePercentTicket',
        imgProduct: 'img.vtex-product-summary-2-x-image',
        nameProduct: '.vtex-product-summary-2-x-productNameContainer--product-card',
        priceProduct: '.arcelormittal-product-price-custom-0-x-productPrice',
        discountTicket:'div.vtex-rich-text-0-x-wrapper--ticket-discount',
        discountPercentage: 'div.vtex-rich-text-0-x-wrapper--priceSavingText',
        buttonAdd: 'button.vtex-button',
    },

    NEWSLETTER_FORM: {
        newsletterContainer: "div[class*='vtex-store-footer-'] > div[class*='vtex-flex-layout-']:nth-of-type(1) > div[class*='flex'] > div[class*='pr'] > div[class*='vtex-flex-layout-']",
        newsLetterTitle: '.vtex-rich-text-0-x-paragraph.vtex-rich-text-0-x-paragraph--newsletter-title-text',
        newsLetterBtn: '.vtex-store-link-0-x-label.vtex-store-link-0-x-label--newsletter-submit-button'
    },
}